audfo=$(termux-audio-info)
PROPERTY_OUTPUT_SAMPLE_RATE=$(echo $audfo | jq ".PROPERTY_OUTPUT_SAMPLE_RATE" -r)
PROPERTY_OUTPUT_FRAMES_PER_BUFFER=$(echo $audfo | jq ".PROPERTY_OUTPUT_FRAMES_PER_BUFFER" -r)
AUDIOTRACK_SAMPLE_RATE=$(echo $audfo | jq ".AUDIOTRACK_SAMPLE_RATE" -r)
AUDIOTRACK_BUFFER_SIZE_IN_FRAMES=$(echo $audfo | jq ".AUDIOTRACK_BUFFER_SIZE_IN_FRAMES" -r)
AUDIOTRACK_SAMPLE_RATE_LOW_LATENCY=$(echo $audfo | jq ".AUDIOTRACK_SAMPLE_RATE_LOW_LATENCY" -r)
AUDIOTRACK_BUFFER_SIZE_IN_FRAMES_LOW_LATENCY=$(echo $audfo | jq ".AUDIOTRACK_BUFFER_SIZE_IN_FRAMES_LOW_LATENCY" -r)
BLUETOOTH_A2DP_IS_ON=$(echo $audfo | jq ".BLUETOOTH_A2DP_IS_ON" -r)
WIREDHEADSET_IS_CONNECTED=$(echo $audfo | jq ".WIREDHEADSET_IS_CONNECTED" -r)


value="    PROPERTY_OUTPUT_SAMPLE_RATE:  $PROPERTY_OUTPUT_SAMPLE_RATE\n    PROPERTY_OUTPUT_FRAMES_PER_BUFFER:  $PROPERTY_OUTPUT_FRAMES_PER_BUFFER\n    AUDIOTRACK_SAMPLE_RATE:  $AUDIOTRACK_SAMPLE_RATE\n    AUDIOTRACK_BUFFER_SIZE_IN_FRAMES:  $AUDIOTRACK_BUFFER_SIZE_IN_FRAMES\n    AUDIOTRACK_SAMPLE_RATE_LOW_LATENCY:  $AUDIOTRACK_SAMPLE_RATE_LOW_LATENCY\n    AUDIOTRACK_BUFFER_SIZE_IN_FRAMES_LOW_LATENCY:  $AUDIOTRACK_BUFFER_SIZE_IN_FRAMES_LOW_LATENCY\n    BLUETOOTH_A2DP_IS_ON:  $BLUETOOTH_A2DP_IS_ON\n    WIREDHEADSET_IS_CONNECTED:  $WIREDHEADSET_IS_CONNECTED"
echo -e $value
echo
read -p $"Press anything to continue" x
